##
# install CakeDC Plugins
# http://cakedc.github.com/
##

# install Utils
- plugin:
    name: Utils
    repo: -f -b 2.0 https://github.com/CakeDC/utilss.git
    target: plugins/Utils

# install Search
- plugin:
    name: Search
    repo: -f -b 2.0 https://github.com/CakeDC/search.git
    target: plugins/Search

# install Migrations
- plugin:
    name: Migrations
    repo: -f -b 2.0 https://github.com/CakeDC/migrations.git
    target: plugins/Migrations

# install Users
- plugin:
    name: Users
    repo: -f -b 2.0 https://github.com/CakeDC/users.git
    target: plugins/Users

# install Categories
- plugin:
    name: Categories
    repo: -f -b 2.0 https://github.com/CakeDC/categories.git
    target: plugins/Categories

# install Recaptcha
- plugin:
    name: Recaptcha
    repo: -f -b 2.0 https://github.com/CakeDC/recaptcha.git
    target: plugins/Recaptcha

# install Tags
- plugin:
    name: Tags
    repo: -f -b 2.0 https://github.com/CakeDC/tags.git
    target: plugins/Tags

# install Comments
- plugin:
    name: Comments
    repo: -f -b 2.0 https://github.com/CakeDC/comments.git
    target: plugins/Comments

# install Templates
- plugin:
    name: Templates
    repo: -f -b 2.0 https://github.com/CakeDC/templates.git
    target: plugins/Templates

# install Favorites
- plugin:
    name: Favorites
    repo: -f -b 2.0 https://github.com/CakeDC/favorites.git
    target: plugins/Favorites

# install Ratings
- plugin:
    name: Ratings
    repo: -f -b 2.0 https://github.com/CakeDC/ratings.git
    target: plugins/Ratings

# install Problems
- plugin:
    name: Problems
    repo: -f -b 2.0 https://github.com/CakeDC/problems.git
    target: plugins/Problems
