##
# Kickstart CakePHP Project
##

# install DebugKit
- git_submodule:
    repo: -f -b 2.0 https://github.com/cakephp/debug_kit.git
    target: plugins/DebugKit
- exec:
    - echo ""  >> {$APP}/Config/bootstrap.php
    - echo "CakePlugin::load('DebugKit');" >> {$APP}/Config/bootstrap.php
    - echo ""  >> {$APP}/Config/bootstrap.php

##
## (using application skelton sample)
##
## install CakePHP skel
#- git_submodule:
#    repo: -f http://github.com/nojimage/CakePHP-skel.git
#    target: plugins/skel

## bake new project
#- exec: rm -r {$APP_DIR}
#- bake: project {$APP_DIR} -app . -skel plugins/skel/basic

# set writable APP/tmp
- exec:
    - chmod -R o+w {$APP}/tmp/

# bake database.php
- bake: db_config
