##
# Kickstart CakePHP Project
##

# install DebugKit
- plugin:
    name: DebugKit
    repo: -f -b 2.0 https://github.com/cakephp/debug_kit.git
    target: plugins/DebugKit

##
## (using application skelton sample)
##
## install CakePHP skel
#- plugin:
#    name: plugins/Skel
#    repo: -f -b 2.0 http://github.com/nojimage/CakePHP-skel.git
#    target: plugins/Skel

## bake new project
#- exec: rm -r {$APP_DIR}
#- bake: project {$APP_DIR} -app . -skel plugins/Skel/basic

# set writable APP/tmp
- exec:
    - chmod -R o+w {$APP}/tmp/

# bake database.php
- bake: db_config
